[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha1 = "0.10"
toml = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rexie = { version = "0.6", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
web-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }

[features]
default = []
web = ["rexie", "wasm-bindgen", "js-sys", "serde-wasm-bindgen", "web-sys"]
