[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components" }
api = { workspace = true }
store = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Location"] }
js-sys = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }

[features]
server = ["api/server"]
